/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.formulario;

/**
 *
 * @author DANIELALEJANDROMIRAN
 */
public class Calculadora extends javax.swing.JFrame {
    boolean NumberPI_E=false;
    String Guia="";
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 50, 52));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(50, 50, 52));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("2nd");
        jButton1.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton1);

        jButton2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton2.setText("PI");
        jButton2.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton3.setText("e");
        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton4.setText("D2");
        jButton4.setBorder(null);
        jButton4.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton5.setText("DEL");
        jButton5.setBorder(null);
        jButton5.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setText("x2");
        jButton6.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton6);

        jButton7.setText("1/X");
        jButton7.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton7);

        jButton8.setText("ABS");
        jButton8.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton8);

        jButton9.setText("EXP");
        jButton9.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton9);

        jButton10.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton10.setText("MOD");
        jButton10.setBorder(null);
        jButton10.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton10);

        jButton11.setText("srpt2");
        jButton11.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton11);

        jButton12.setText("(");
        jButton12.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton12);

        jButton13.setText(")");
        jButton13.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton13);

        jButton14.setText("N!");
        jButton14.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton14);

        jButton15.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton15.setText("/");
        jButton15.setBorder(null);
        jButton15.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        jPanel2.add(jButton15);

        jButton16.setText("xY");
        jButton16.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton16);

        jButton17.setText("7");
        jButton17.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        jPanel2.add(jButton17);

        jButton18.setText("8");
        jButton18.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        jPanel2.add(jButton18);

        jButton19.setText("9");
        jButton19.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });
        jPanel2.add(jButton19);

        jButton20.setText("X");
        jButton20.setAlignmentX(0.5F);
        jButton20.setBorder(null);
        jButton20.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton20MouseClicked(evt);
            }
        });
        jPanel2.add(jButton20);

        jButton21.setText("10x");
        jButton21.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton21);

        jButton22.setText("4");
        jButton22.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });
        jPanel2.add(jButton22);

        jButton23.setText("5");
        jButton23.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton23MouseClicked(evt);
            }
        });
        jPanel2.add(jButton23);

        jButton24.setText("6");
        jButton24.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton24MouseClicked(evt);
            }
        });
        jPanel2.add(jButton24);

        jButton25.setText("-");
        jButton25.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton25MouseClicked(evt);
            }
        });
        jPanel2.add(jButton25);

        jButton26.setText("Log");
        jButton26.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton26);

        jButton27.setText("1");
        jButton27.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton27MouseClicked(evt);
            }
        });
        jPanel2.add(jButton27);

        jButton28.setText("2");
        jButton28.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton28MouseClicked(evt);
            }
        });
        jPanel2.add(jButton28);

        jButton29.setText("3");
        jButton29.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton29MouseClicked(evt);
            }
        });
        jPanel2.add(jButton29);

        jButton30.setText("+");
        jButton30.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton30MouseClicked(evt);
            }
        });
        jPanel2.add(jButton30);

        jButton31.setText("In");
        jButton31.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton31);

        jButton32.setText("+/-");
        jButton32.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton32);

        jButton33.setText("0");
        jButton33.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton33MouseClicked(evt);
            }
        });
        jPanel2.add(jButton33);

        jButton34.setText(",");
        jButton34.setPreferredSize(new java.awt.Dimension(70, 32));
        jPanel2.add(jButton34);

        jButton35.setText("=");
        jButton35.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton35MouseClicked(evt);
            }
        });
        jPanel2.add(jButton35);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 263, 380, 267));

        jTextField1.setBackground(new java.awt.Color(50, 50, 52));
        jTextField1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 380, 35));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(50, 50, 52));
        jTextField2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 380, 35));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(50, 50, 52));
        jTextField3.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 380, 40));

        jMenuBar1.setBorder(null);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton33MouseClicked
        jTextField1.setText(jTextField1.getText()+0);
    }//GEN-LAST:event_jButton33MouseClicked

    private void jButton27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseClicked
        jTextField1.setText(jTextField1.getText()+1);
    }//GEN-LAST:event_jButton27MouseClicked

    private void jButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseClicked
        jTextField1.setText(jTextField1.getText()+2);
    }//GEN-LAST:event_jButton28MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if(jTextField1.getText().isEmpty()==false){
            jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getText().length()-1));
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton29MouseClicked
       jTextField1.setText(jTextField1.getText()+3);
    }//GEN-LAST:event_jButton29MouseClicked

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        jTextField1.setText(jTextField1.getText()+4);
    }//GEN-LAST:event_jButton22MouseClicked

    private void jButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseClicked
        jTextField1.setText(jTextField1.getText()+5);
    }//GEN-LAST:event_jButton23MouseClicked

    private void jButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseClicked
        jTextField1.setText(jTextField1.getText()+6);
    }//GEN-LAST:event_jButton24MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        jTextField1.setText(jTextField1.getText()+7);
    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        jTextField1.setText(jTextField1.getText()+8);
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
        jTextField1.setText(jTextField1.getText()+9);
    }//GEN-LAST:event_jButton19MouseClicked

    private void jButton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseClicked
        
        Guia="+";
        jTextField2.setText(jTextField1.getText());
        jTextField1.setText("");
    }//GEN-LAST:event_jButton30MouseClicked

    private void jButton35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton35MouseClicked

        
        switch(Guia){
            case("+"):
                if(NumberPI_E!=true){
                    jTextField3.setText(""+((Long) Long.valueOf(jTextField2.getText())+(Long) Long.valueOf(jTextField1.getText())));
                } else if (NumberPI_E==true){
                    jTextField3.setText(""+((double) Double.valueOf(jTextField2.getText())+(double) Double.valueOf(jTextField1.getText())));
                }
                break;
            case("-"):
                if(NumberPI_E!=true){
                    jTextField3.setText(""+((Long) Long.valueOf(jTextField2.getText())-(Long) Long.valueOf(jTextField1.getText())));
                } else if (NumberPI_E==true){
                    jTextField3.setText(""+((double) Double.valueOf(jTextField2.getText())-(double) Double.valueOf(jTextField1.getText())));
                }
                break;
            case("*"):
                if(NumberPI_E!=true){
                    jTextField3.setText(""+((Long) Long.valueOf(jTextField2.getText())*(Long) Long.valueOf(jTextField1.getText())));
                } else if (NumberPI_E==true){
                    jTextField3.setText(""+((double) Double.valueOf(jTextField2.getText())*(double) Double.valueOf(jTextField1.getText())));
                }
                break;
            case("/"):
                jTextField3.setText(""+((Double) Double.valueOf(jTextField2.getText())/(Double) Double.valueOf(jTextField1.getText())));
                break;
        }
        NumberPI_E=false;
    }//GEN-LAST:event_jButton35MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        NumberPI_E=false;
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseClicked
        Guia="-";
        jTextField2.setText(jTextField1.getText());
        jTextField1.setText("");
    }//GEN-LAST:event_jButton25MouseClicked

    private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
        Guia="*";
        jTextField2.setText(jTextField1.getText());
        jTextField1.setText("");
    }//GEN-LAST:event_jButton20MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        Guia="/";
        jTextField2.setText(jTextField1.getText());
        jTextField1.setText("");
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jTextField1.setText(jTextField1.getText()+(double) Math.PI);
        NumberPI_E=true;
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jTextField1.setText(jTextField1.getText()+(double) Math.E);
        NumberPI_E=true;
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
